### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by 42Stuff** [Portugao/Blogging#12]
Zikula 2.0.12 Blogging 1.2.0

When creating or updating a post, the 'Image for article:' fails with 'this value is not valid.  Used the Browse Button to select a local file (jpg).  The Post is saved as far as the Text entries are concerned, but cannot get an image to upload.

**Comment by Guite** [comment]
To make it work please replace
```
                'error_bubbling' => false
```
by
```
                'error_bubbling' => false,
                'allow_file_upload' => true
```

in https://github.com/Portugao/Blogging/blob/master/MU/BloggingModule/Form/Type/Field/Base/AbstractUploadType.php#L164

This is a regression in a recent Symfony version and the patch will be included in a future regeneration of the module.

**Comment by 42Stuff** [comment]
Thanks Guite.  That nailed it.

**Comment by Guite** [comment]
Changed generator to provide that for Zikula 2.0.12 https://github.com/Guite/MostGenerator/commit/c5b34a9d28e0d75e541d2a992bb946224c72dc0f
