### ISSUE TITLE
Choosing none may not give an empty result

### ISSUE THREAD

**Issue by Portugao** [Portugao/Blogging#8]

**Comment by Portugao** [comment]
@guite, i have a list with values of existing articles.
A value 'none' for choosing no article does not get work because it is an unvalid value.
Do you have an idea how to fix that? I have tried many ways...that do not help

**Comment by Guite** [comment]
adding `'required' => false,` to the form field?

**Comment by Portugao** [comment]
Had tried that, does not help.
In MOST I have to define one, better two list items.
In my case I choosed 'none' and 'all'. Then a value like '' or 0 is not valid?

**Comment by Portugao** [comment]
Have to rename this issue.
Problem is, that choosing none gives an empty result back, that is shown in the relevant conatiner.
